### ISSUE TITLE
Fix incorrect filenames and missing symbols

### ISSUE THREAD

**Issue by rusnewman** [straight-street/mulberry-symbols#5]
I've identified some consistency issues in the symbol set as a result of some tests involving this repo.

### Symbols listed in CSV with incorrect SVG filenames
Some SVG files appear to have names that are not consistent with those provided in the CSV file. Here's a list that was generated by one of my tests (i.e. it should be a complete list).

```
# Key:   filename of SVG as stated in CSV file
# Value: actual filename of SVG
wrong_filename_mappings = {
  'blender_drinks': 'blender-drinks',
  'tv_change_channel': 'change_tv_channel_,_to',
  'football_dribble': 'dribble_football_,_to',
  'features': 'features_facial',
  'open_computer_folder_,_to': 'computer_folder_open_,_to',
  'score_goal': 'score_goal_,_to',
  'send_email_,_to': 'email_send_,_to',
  'sit_at_computer_2_,_to': 'sit_at_computer_,_to_2',
  'television_switch_on': 'switch_on_television_,_to',
  'light_switch_turn_off': 'turn_off_light_switch_,_to'
}
```
In some cases, the SVG should be renamed (e.g. blender-drinks.svg should be blender_drinks.svg, making it consistent with other files that write spaces as underscores). In other cases, the CSV needs updating.

### Symbols listed in CSV with missing SVG files
Some rows in the CSV file are missing SVGs completely (or perhaps I've been unable to identify the correct SVG from the name in the CSV). Again, this is generated by tests, so this should be an exhaustive list. They are:

- mobile_phone_adaptor
- nails
- glass_2
- receive_email_,_to

### SVG files that have no entry in the CSV file
I have not done this test, so there could be SVGs which are not listed in the CSV file.

**Comment by SteveALee** [comment]
@rusnewman thank you very much for this. I've no idea how those errors sneaked in!

I'll make the updates asap. 

Incidently we had some translations which I intend to add to the csv once I get hold of them again.

**Comment by SteveALee** [comment]
Are your testing something that could easily be added to the repositry and added to the release process as a sanity check?

**Comment by rusnewman** [comment]
Thanks Steve! I'm afraid the tests are specific to the application I'm working on, so not exactly transferrable.

Incidentally, I'm using the first column of the CSV as a unique identifier for each symbol. If a unique identifier disappears from the CSV, I would (currently) see this as an indication that the symbol has been deleted.

I can handle the data in this column changing as a result of this ticket, but can I depend on it remaining static in the future?

Thanks

**Comment by rusnewman** [comment]
Thanks Steve! I'm afraid the tests are specific to the application I'm working on, so not exactly transferrable.

Incidentally, I'm using the first column of the CSV as a unique identifier for each symbol. If a unique identifier disappears from the CSV, I would (currently) see this as an indication that the symbol has been deleted.

I can handle the data in this column changing as a result of this ticket, but can I depend on it remaining static in the future?

Thanks

**Comment by SteveALee** [comment]
> I'm afraid the tests are specific to the application I'm working on, so not exactly transferrable
never mind - I added a little test script. Seem quite a few files are missing

**Comment by SteveALee** [comment]
All done. 

* Added reconciliation test
* Corrected all symbols or filenames so they reconcile - file `receive_email_,_to` Still Missing
* Added Missing files to csv
* Added ID column symbols will always keep the same id even if renamed
* Add separate Finnish translation csv for future use.

**Comment by SteveALee** [comment]
@rusnewman see release v3.2 for more symbols
